### ISSUE TITLE
Does the wallet send the private keys to arborwallet.com?

### ISSUE THREAD

**Issue by pestotoast** [Digital-Farming-Initiative/arbor-wallet#33]
I have been reviewing the code of this app and I have a few questions:

In [wallet-service.dart](https://github.com/Digital-Farming-Initiative/arbor-wallet/blob/6353bdebe6c4caf20efc374204ff86e19873cdff/lib/api/services/wallet_service.dart#L295) it looks like the app is sending the private keys to the server:

```
Future<dynamic> sendXCH(
      {required String privateKey,
      required var amount,
      required String address,required int fee}) async {
    try {
      final responseData = await http.post(
        Uri.parse('${baseURL}/v1/send'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'private_key': privateKey,
          'amount': amount,
          'destination': address,
          'fee': fee
        }),
      );

```

 Is that correct or am I missing something? If yes, that's a huge security risk.

And the [recoverWallet function](https://github.com/Digital-Farming-Initiative/arbor-wallet/blob/6353bdebe6c4caf20efc374204ff86e19873cdff/lib/api/services/wallet_service.dart#L98)  seems to be sending the seed to the server:

```
// @POST("/v1/recover") and @POST("/v1/wallet") and @POST("v1/blockchain") and @POST("/v1/balance")
  Future<Wallet> recoverWallet(String phrase)async{
    try{

      final recoverKeyResponse = await http.post(
        Uri.parse('${baseURL}/v1/recover'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, String>{
          'phrase': phrase,
        }),
      );

```

Is that assumption correct? On arborwallet.com you explicitly say that private keys would never leave the device!

**Comment by scotopic** [comment]
UPDATE: As of [Arbor Wallet v2.0.0](https://github.com/Digital-Farming-Initiative/arbor-wallet/releases/tag/2.0.0) we now have everything in-app/locally generating/signing. All backend API is now removed. Please feel free to verify.
