### ISSUE TITLE
Private Keys generated in the API end point

### ISSUE THREAD

**Issue by Ganbin** [Digital-Farming-Initiative/arbor-wallet#36]
After reading the code of the [api_service.dart](https://github.com/Digital-Farming-Initiative/arbor-wallet/blob/develop/lib/api/services/wallet_service.dart) and this particular function : 

[Future<Wallet> createNewWallet()async](https://github.com/Digital-Farming-Initiative/arbor-wallet/blob/6353bdebe6c4caf20efc374204ff86e19873cdff/lib/api/services/wallet_service.dart#L19-L95)

We can see that the private keys are generated in the API end point and are then sent to the client.

As the issue #33, this is a concern because the private keys should never leave the user device.

I suppose that when you will be fixing the #33 by having all the necessary libraries on the client to sign a transaction bundle  with the private keys, you will be able to generate the key, for a new wallet, on the device directly.

**Comment by scotopic** [comment]
UPDATE: As of [Arbor Wallet v2.0.0](https://github.com/Digital-Farming-Initiative/arbor-wallet/releases/tag/2.0.0) we now have everything in-app/locally generating/signing. All backend API is now removed. Please feel free to verify.
