### ISSUE TITLE
Can not send any sum of XCH! Oops! Could not push transaction

### ISSUE THREAD

**Issue by igor-1964** [Digital-Farming-Initiative/arbor-wallet#45]
Hello. I can not send my coins from Arbor Wallet. It says "Oops! Could not push transaction". I have tried at my android as well as my iPhone. This error is the same on both.
Please correct this issue because I can not get my money.
Thanks.

**Comment by scotopic** [comment]
Can you try again? Looks like our Chia full node fell behind sync and now appears to be back up.

**Comment by Rigidity** [comment]
This issue should be resolved, let us know if you have any other problems.
