### ISSUE TITLE
Can't restore Wallet

### ISSUE THREAD

**Issue by dsqwared5** [Digital-Farming-Initiative/arbor-wallet#47]
Hello, I download new app, and tried to restore my wallet, fill all 12 words, pushing restore, than seeing preloader, and after 10-15 sec button again available and nothing happened

**Comment by scotopic** [comment]
Sadly, this service/wallet has been shutdown. Try using your mnemonic in a different wallet either official Chia wallet or Evergreen mobile wallet.
